AppBasicoMvcSaeInfo/Controllers/AlunosController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using AppBasicoMvcSaeInfo.Data.Contexto;
using AppBasicoMvcSaeInfo.Models;
using AppBasicoMvcSaeInfo.Data.Interface;
using AppBasicoMvcSaeInfo.Data.Services;
using AppBasicoMvcSaeInfo.Data.Repositorio;
using ReflectionIT.Mvc.Paging;

namespace AppBasicoMvcSaeInfo.Controllers
{
    public class AlunosController : Controller
    {
        private readonly MeuDbContext _context;
        private readonly IAlunoRepositorio _alunoRepositorio;
        private readonly AlunoService _alunoService;

        public AlunosController(MeuDbContext meuDbContext)
        {
            _context = meuDbContext;
            _alunoRepositorio = new AlunoRepositorio(_context);
            _alunoService = new AlunoService();
        }

        public async Task<IActionResult> Index(string sortOrder, int page = 1)
        {
            var alunos = _alunoRepositorio.ObterTodosAlunosInclude().AsNoTracking().OrderBy(x => x.Nome);
            alunos = OrdernarGrid(sortOrder, alunos);
            var model = await PagingList.CreateAsync(alunos, 10, page);

            return View(model);
        }

        public async Task<IActionResult> Detalhes(Guid? id)
        {
            if (id == null)
                return NotFound();

            var aluno = await _context.Alunos.Include(x => x.Endereco).FirstOrDefaultAsync(x => x.Id == id);

            if (aluno == null)
                return NotFound();

            return View(aluno);
        }

        public IActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Criar(Aluno aluno)
        {
            if (ModelState.IsValid)
            {
                await _alunoRepositorio.Adicionar(aluno);
                return RedirectToAction("Index");
            }
            return View(aluno);
        }

        public async Task<IActionResult> Editar(Guid? id)
        {
            if (id == null)
                return NotFound();

            var aluno = await _context.Alunos.Include(x => x.Responsaveis) .Include(x => x.Endereco).FirstOrDefaultAsync(f => f.Id == id);

            if (aluno == null)
                return NotFound();

            return View(aluno);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(Guid id, Aluno aluno)
        {
            if (id != aluno.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                await _alunoRepositorio.Atualizar(aluno);
                return RedirectToAction("Index");
            }
            return View(aluno);
        }

        public async Task<IActionResult> Deletar(Guid? id)
        {
            if (id == null)
                return NotFound();

            var aluno = await _context.Alunos.Include(x => x.Endereco).FirstOrDefaultAsync(f => f.Id == id);

            if (aluno == null)
                return NotFound();

            return View(aluno);
        }

        [HttpPost, ActionName("Deletar")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmaDelete(Guid id)
        {
            await _alunoRepositorio.Remover(id);
            return RedirectToAction("Index");
        }

        public IOrderedQueryable<Aluno> OrdernarGrid(string sortOrder, IOrderedQueryable<Aluno> aluno)
        {
            ViewData["OrdenarNome"] = string.IsNullOrEmpty(sortOrder) ? "nomeDesc" : "";
            ViewData["OrdenarCpf"] = string.IsNullOrEmpty(sortOrder) ? "cpfDesc" : "";
            ViewData["OrdenarDataCadastro"] = sortOrder == "dataCadastro" ? "dataDesc" : "dataCadastro";
            ViewData["OrdenarSexo"] = string.IsNullOrEmpty(sortOrder) ? "sexoDesc" : "";
            ViewData["OrdenarCidade"] = string.IsNullOrEmpty(sortOrder) ? "cidadeDesc" : "";

            aluno = _alunoService.OrdernarGrid(sortOrder, aluno);
            return aluno;
        }
    }
}

AppBasicoMvcSaeInfo/Controllers/AlunosPorCidadeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AppBasicoMvcSaeInfo.Data.Contexto;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AppBasicoMvcSaeInfo.Controllers
{
    public class AlunosPorCidadeController : Controller
    {
        private readonly MeuDbContext _context;

        public AlunosPorCidadeController(MeuDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> BuscarCidade()
        {
            var cidades = await _context.Cidades.ToListAsync();

            return View(cidades);
        }

        public async Task<IActionResult> BuscarAlunoPorCidade(Guid? id)
        {
            if (id == null)
                return NotFound();

            var alunosLista = _context.Alunos.Include(x => x.Endereco.Cidade);

            return View(await alunosLista.Where(x => x.Endereco.Cidade.Id == id).ToListAsync());
        }
    }
}

AppBasicoMvcSaeInfo/Controllers/CidadesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AppBasicoMvcSaeInfo.Data.Contexto;
using AppBasicoMvcSaeInfo.Models;
using AppBasicoMvcSaeInfo.Data.Interface;
using AppBasicoMvcSaeInfo.Data.Repositorio;
using ReflectionIT.Mvc.Paging;
using AppBasicoMvcSaeInfo.Data.Services;

namespace AppBasicoMvcSaeInfo.Controllers
{
    public class CidadesController : Controller
    {
        private readonly MeuDbContext _context;
        private readonly ICidadeRepositorio _cidadeRepositorio;
        private readonly CidadeService _cidadeService;

        public CidadesController(MeuDbContext context)
        {
            _context = context;
            _cidadeRepositorio = new CidadeRepositorio(_context);
            _cidadeService = new CidadeService();
        }

        public async Task<IActionResult> Index(string sortOrder, int page = 1)
        {
            var cidades = _cidadeRepositorio.ObterTodosAlunosInclude().AsNoTracking().OrderBy(x => x.Nome);
            cidades = OrdernarGrid(sortOrder, cidades);
            var model = await PagingList.CreateAsync(cidades, 5, page);

            return View(model);
        }

        public async Task<IActionResult> Detalhes(Guid? id)
        {
            if (id == null)
                return NotFound();

            var cidade = await _context.Cidades.Include(x => x.Estado).FirstOrDefaultAsync(x => x.Id == id);

            if (cidade == null)
                return NotFound();

            return View(cidade);
        }

        public IActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Criar(Cidade cidade)
        {
            if (ModelState.IsValid)
            {
                await _cidadeRepositorio.Adicionar(cidade);
                return RedirectToAction(nameof(Index));
            }
            return View(cidade);
        }

        public async Task<IActionResult> Editar(Guid? id)
        {
            if (id == null)
                return NotFound();

            var cidade = await _context.Cidades.Include(x => x.Estado).FirstOrDefaultAsync(x => x.Id == id);

            if (cidade == null)
                return NotFound();

            return View(cidade);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(Guid id, Cidade cidade)
        {
            if (id != cidade.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                await _cidadeRepositorio.Atualizar(cidade);
                return RedirectToAction("Index");
            }
            return View(cidade);
        }

        public async Task<IActionResult> Deletar(Guid? id)
        {
            if (id == null)
               return NotFound();

            var cidade = await _context.Cidades.Include(x => x.Estado).FirstOrDefaultAsync(m => m.Id == id);

            if (cidade == null)
                return NotFound();

            return View(cidade);
        }

        [HttpPost, ActionName("Deletar")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmaDelete(Guid id)
        {
            await _cidadeRepositorio.Remover(id);
            return RedirectToAction("Index");
        }

        public IOrderedQueryable<Cidade> OrdernarGrid(string sortOrder, IOrderedQueryable<Cidade> cidade)
        {
            ViewData["OrdenarCidade"] = string.IsNullOrEmpty(sortOrder) ? "cidadeDesc" : "";
            ViewData["OrdenarEstado"] = string.IsNullOrEmpty(sortOrder) ? "estadoDesc" : "";

            cidade = _cidadeService.OrdernarGrid(sortOrder, cidade);
            return cidade;
        }
    }
}

AppBasicoMvcSaeInfo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SaeInfo MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppBasicoMvcSaeInfo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Alunos" asp-action="Index">Alunos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cidades" asp-action="Index">Cidades</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AlunosPorCidade" asp-action="BuscarCidade">Alunos por Cidade</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SaeInfo
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>